@startuml
title Data Flow for Native Transaction Builder
skinparam rectangle {
  BackgroundColor LightPink
}
skinparam storage {
  BackgroundColor LightCyan
}
skinparam collections {
  BackgroundColor LightGreen
}
storage List as list_of_UTxOs {
  collections UTxOs [
    UTxO
    ==
    Box box
    BoxId id
    TypedEvidence address
  ]
}
storage List as list_of_predicates {
  collections predicate
}
rectangle buildInputs
storage List as listOfUnprovenInputs {
  collections UnprovenInput [
    UnprovenInput
    ==
    BoxId id
    Proposition proposition
    LvlBoxValue
  ]
}
storage creationTimestamp
storage minimumSlot
storage maximumSlot
storage schedule [
Schedule
==
uint64 creationTimestamp
uint64 minimumSlot
uint64 maximumSlot
]
rectangle constructSchedule
storage quantity
rectangle constructLvlBoxValue
storage LvlBoxValue [
  LvlBoxValue
  ==
  Int128 quantity
]
storage networkPrefix
storage spendingAddress
rectangle constructOutput
storage Output [
  Output
  ==
  TypedEvidence address
  LvlBoxValue value
  Option[Minting] minting = None
]
storage List as list_of_outputs {
    collections output
}
storage transactionData
storage transactionDataHash
rectangle unprovenTransactionBuilder
storage UnprovenTransaction [
  UnprovenTransaction
  ==
  List[UnprovenInput] inputs
  List[Output] outputs
  Schedule schedule
  bytes transactionData
  bytes transactionDataHash
]

creationTimestamp --> constructSchedule
minimumSlot -> constructSchedule
constructSchedule <-- maximumSlot
constructSchedule -> schedule

buildInputs <- list_of_predicates
list_of_UTxOs --> buildInputs
buildInputs --> listOfUnprovenInputs

quantity -> constructLvlBoxValue
constructLvlBoxValue -> LvlBoxValue

note "Must be \nthe same length" as N1
N1 .. list_of_predicates
list_of_UTxOs .. N1

networkPrefix -> constructOutput
LvlBoxValue --> constructOutput
spendingAddress -->constructOutput
constructOutput -> Output

Output ..o list_of_outputs

unprovenTransactionBuilder <- listOfUnprovenInputs
list_of_outputs --> unprovenTransactionBuilder
schedule -> unprovenTransactionBuilder
unprovenTransactionBuilder <-- transactionData
unprovenTransactionBuilder <-- transactionDataHash
unprovenTransactionBuilder --> UnprovenTransaction
@enduml