@startuml
title Data Flow for Native Transaction Builder
skinparam rectangle {
  BackgroundColor LightPink
}
skinparam storage {
  BackgroundColor LightCyan
}
storage listOfTxos
storage listOfPredicates
rectangle buildInputs
storage listOfUnprovenInputs

listOfTxos -> buildInputs
listOfPredicates -> buildInputs
buildInputs -> listOfUnprovenInputs

listOfTxos -[hidden]- listOfPredicates
@enduml