@startuml
title Data Flow for Native Transaction Builder
skinparam rectangle {
  BackgroundColor LightPink
}
skinparam storage {
  BackgroundColor LightCyan
}
skinparam collections {
  BackgroundColor LightGreen
}
storage list as list_of_UTxOs {
  collections UTxOs [
    UTxOs
    ==
    Box box
    BoxId id
    SpendingAddress address
  ]
}
storage list as list_of_predicates {
  collections predicates
}
rectangle buildInputs
storage listOfUnprovenInputs
storage creationTimestamp
storage minimumSlot
storage maximumSlot
storage schedule [
schedule
==
uint64 creationTimestamp
uint64 minimumSlot
uint64 maximumSlot
]
rectangle constructSchedule
storage quantity
rectangle constructLvlBoxValue
storage lvlBoxValue

creationTimestamp --> constructSchedule
minimumSlot -> constructSchedule
constructSchedule <-- maximumSlot
constructSchedule -> schedule

list_of_predicates -> buildInputs
list_of_UTxOs --> buildInputs
buildInputs -> listOfUnprovenInputs

quantity -> constructLvlBoxValue
constructLvlBoxValue -> lvlBoxValue

note "Must be \nthe same length" as N1
N1 .. list_of_predicates
N1 . list_of_UTxOs
@enduml